version: '3.4'

services:
  rabbitserver:
    image: rabbitmq:3-management
    hostname: rabbitserver
    networks:
      - taskmanagernet
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
        test: rabbitmq-diagnostics -q status && rabbitmq-diagnostics -q ping && check_port_connectivity
        interval: 5s
        timeout: 5s
        retries: 5

  taskmanager.webapi:
    image: ${DOCKER_REGISTRY-}taskmanagerwebapi
    build:
      context: .
      dockerfile: TaskManager.WebAPI/Dockerfile
    ports:
      - "5020:5020"
    networks:
      - taskmanagernet
    healthcheck:
        test: ["CMD","curl", "-f", "http://localhost:5020/healthcheck"]
        interval: 5s
        timeout: 5s
        retries: 5
    restart: on-failure
    depends_on:
      - rabbitserver
    links: 
        - rabbitserver

  taskmanager.worker:
    image: ${DOCKER_REGISTRY-}taskmanagerworker
    build:
      context: .
      dockerfile: TaskManager.Worker/Dockerfile
    environment:
      - RABBITMQ_CONNECTION_STRING=rabbitserver
    networks:
      - taskmanagernet
    restart: on-failure
    depends_on:
      - rabbitserver
    links: 
        - rabbitserver

networks:
  taskmanagernet:
    driver: bridge
    ipam:
      driver: default