version: '3.4'

services:
  rabbitserver:
    image: rabbitmq:3-management
    hostname: rabbitserver
    networks:
      - taskmanagernet
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"

  taskmanager.webapi:
    image: ${DOCKER_REGISTRY-}taskmanagerwebapi
    build:
      context: .
      dockerfile: TaskManager.WebAPI/Dockerfile
    ports:
      - "5020:5020"
    networks:
      - taskmanagernet
    healthcheck:
        test: ["CMD","curl", "-f", "http://localhost:5020/healthcheck"]
        interval: 30s
        timeout: 10s
        retries: 5
    depends_on:
      - rabbitserver
  
  taskmanager.worker:
    image: ${DOCKER_REGISTRY-}taskmanagerworker
    build:
      context: .
      dockerfile: TaskManager.Worker/Dockerfile
    environment:
      - RABBITMQ_CONNECTION_STRING=rabbitserver
    networks:
      - taskmanagernet
    depends_on:
      rabbitserver:
        condition: service_started
      taskmanager.webapi:
        condition: service_healthy
        
networks:
  taskmanagernet:
    driver: bridge
    ipam:
      driver: default